### PR TITLE
Remove dot and add domain path

### PR DESCRIPTION
**Pull request by huubl**
Hi,

There is a problem with translations:
image

https://translate.wordpress.org/projects/wp-plugins/post-lockdown/

I'm not sure, but maybe this will fixed it.

### CODE REVIEW

**Comment by huubl** [comment]
Thanks! Version is still 3.0.6 on https://wordpress.org/plugins/post-lockdown/ btw :)

**Comment by andyexeter** [comment]
@huubl yes sorry, I didn’t get a chance to release a new version yet. Will do it tonight or tomorrow :)

I’m not too familiar with localisation in WordPress plugins. Will it “just work” with these changes or do we actually need translations for each language in the languages directory?

**Comment by huubl** [comment]
@andyexeter Sorry didn't mean to push you, I saw version [3.0.7](https://wordpress.org/plugins/post-lockdown/#developers) in WP changelog and assumed something went wrong :) But great to hear you're planning to release an update soon! Regarding localization in WordPress I'm not 100% sure, but checking the docs I think setting "Requires at least: field in your readme.txt to 4.6 or more." is needed.

image
https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain

I made made a [new pull request](https://github.com/andyexeter/post-lockdown/pull/17) that adds "Requires at least: 4.6" and some other comments that maybe could be added (please check if you think they should be added).

**Comment by andyexeter** [comment]
@huubl Yeah I forgot how much of a pain it was working with SVN and had some issues with versioning.

I've just implemented the [10up/action-wordpress-plugin-deploy](https://github.com/10up/action-wordpress-plugin-deploy) Github Action so releases on here will auto deploy to the wp.org plugin repository from now on :smile: 

Thank you for the work you have done, it's much appreciated.

Just about to try deploying for the first time using the new CI/CD workflow :crossed_fingers:

**Comment by huubl** [comment]
@andyexeter I see the updated plugin is now in the wp.org plugin repository, nice that the deployments are automated now too!

I'm glad to hear that you appreciate the contributions 😄

**Pull request merged**
